# springdoc-openapi 项目配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  group-configs:
    - group: 'default'
      packages-to-scan: com.miqroera.biosensor.web
      packages-to-exclude:
        - com.miqroera.biosensor.web.admin
    - group: "admin"
      packages-to-scan:
        - com.miqroera.biosensor.web.admin
# knife4j 的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn