server:
  port: 9093
  servlet:
    context-path: /api

spring:
  application:
    name: mof-based-biosensor
  profiles:
    active: knife4j, dev, mock

logging:
  level:
    com.miqroera: info
    
mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: delFlag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0